/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Read Slack-formatted content from the system clipboard.
 * Returns `plain_text` and `delta_text` (decoded from `org.chromium.web-custom-data`).
 */
export declare function readClipboard(): SlackClipboard

export interface SlackClipboard {
  plainText?: string
  deltaText?: string
}

/**
 * Write Slack-formatted content to the system clipboard.
 * Encodes `delta_text` as a Chromium Pickle under `org.chromium.web-custom-data`
 * with MIME type `slack/texty`, and sets `plain_text` as the plain text fallback.
 */
export declare function writeClipboard(plainText: string, deltaText: string): void
